spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loginapi?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
   port: 8082 # This is the default port anyway, but you can change it here
